import { useEffect, useMemo, useState } from 'react';
import { ImagePlus, Save } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { lineageBenefitText, raceBenefitText } from '@/lib/ancestry';

type Kind='races'|'lineages';
const input='w-full bg-shadow/60 border border-gold-dim rounded-lg px-3 py-2 text-parchment text-sm focus:outline-none focus:border-gold';
const btn='inline-flex items-center gap-2 px-3 py-2 rounded-lg border border-gold-dim text-gold hover:border-gold text-sm';
export default function AncestryAdmin({kind}:{kind:Kind}){
 const [rows,setRows]=useState<any[]>([]),[races,setRaces]=useState<any[]>([]),[selected,setSelected]=useState<any|null>(null),[draft,setDraft]=useState<any|null>(null),[saving,setSaving]=useState(false),[error,setError]=useState('');
 const load=async()=>{setError('');const [a,b]=await Promise.all([supabase.from(kind).select('*').order('name'),supabase.from('races').select('*').order('name')]);if(a.error){setError('As tabelas de ancestralidade ainda não estão disponíveis. Execute a migration 20261003193000_races_lineages.sql no Supabase.');return}setRows(a.data||[]);setRaces(b.data||[]);if(selected){const fresh=(a.data||[]).find((x:any)=>x.id===selected.id);if(fresh){setSelected(fresh);setDraft({...fresh})}}};
 useEffect(()=>{load()},[kind]);
 const grouped=useMemo(()=>kind==='lineages'?races.map(r=>({race:r,items:rows.filter(x=>x.race_id===r.id)})):[],[kind,races,rows]);
 const choose=(r:any)=>{setSelected(r);setDraft({...r})};
 const save=async()=>{if(!draft||!draft.name.trim())return;setSaving(true);const oldName=selected?.name; const {data,error:e}=await supabase.from(kind).update({name:draft.name.trim(),description:draft.description||'',image_url:draft.image_url||''}).eq('id',draft.id).select().single();if(e)alert(e.message);else{if(oldName&&oldName!==draft.name.trim()){if(kind==='races')await supabase.from('characters').update({race:draft.name.trim()}).eq('race',oldName);else await supabase.from('characters').update({lineage:draft.name.trim()}).eq('lineage',oldName)}setSelected(data);setDraft({...data});await load()}setSaving(false)};
 const upload=async(file?:File)=>{if(!file||!draft)return;const ext=file.name.split('.').pop()||'png';const path=`${kind}/${draft.id}-${Date.now()}.${ext}`;const {error:e}=await supabase.storage.from('ancestry-images').upload(path,file,{upsert:true});if(e){alert(e.message);return}const {data}=supabase.storage.from('ancestry-images').getPublicUrl(path);setDraft({...draft,image_url:data.publicUrl})};
 if(error)return <div className="bg-blood/10 border border-blood/40 rounded-xl p-5 text-parchment">{error}</div>;
 const card=(r:any)=><button key={r.id} onClick={()=>choose(r)} className={`text-left rounded-xl border p-3 transition ${selected?.id===r.id?'border-gold bg-gold/10':'border-gold-dim bg-gradient-card hover:border-gold'}`}><div className="flex gap-3 items-center">{r.image_url?<img src={r.image_url} className="w-16 h-16 rounded-lg object-cover border border-gold-dim"/>:<div className="w-16 h-16 bg-shadow rounded-lg"/>}<div className="min-w-0"><b className="font-display text-gold-bright">{r.name}</b><p className="text-[11px] leading-snug text-gold/80 mt-1">{kind==='races'?raceBenefitText(r):lineageBenefitText(r)}</p></div></div></button>;
 return <section className="grid lg:grid-cols-[1fr_1fr] gap-5"><div><h2 className="font-display text-xl text-gold-bright mb-1">{kind==='races'?'Raças':'Linhagens'}</h2><p className="text-xs text-parchment-dim mb-4">Edite nome, imagem e descrição. Os identificadores internos e as regras mecânicas permanecem preservados.</p>{kind==='races'?<div className="grid sm:grid-cols-2 gap-3">{rows.map(card)}</div>:<div className="space-y-5">{grouped.map(g=><div key={g.race.id}><h3 className="font-display text-gold mb-2">{g.race.name}</h3><div className="grid sm:grid-cols-2 gap-3">{g.items.map(card)}</div></div>)}</div>}</div><div>{draft?<div className="bg-gradient-card border border-gold-dim rounded-xl p-5 sticky top-24"><h3 className="font-display text-lg text-gold-bright mb-4">Editar {kind==='races'?'raça':'linhagem'}</h3><div className="space-y-4"><label className="block text-xs text-gold">Nome<input className={`${input} mt-1`} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><div><span className="block text-xs text-gold mb-1">Imagem</span>{draft.image_url&&<img src={draft.image_url} className="w-full max-h-64 object-contain bg-shadow rounded-lg border border-gold-dim mb-2"/>}<label className={`${btn} cursor-pointer`}><ImagePlus className="w-4 h-4"/>Trocar imagem<input type="file" accept="image/*" className="hidden" onChange={e=>upload(e.target.files?.[0])}/></label></div><label className="block text-xs text-gold">Descrição<textarea rows={7} className={`${input} mt-1 resize-y`} value={draft.description||''} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><div className="rounded-lg border border-gold-dim bg-gold/5 p-3"><span className="block text-[10px] uppercase tracking-[.15em] text-gold/70 mb-1">Benefício mecânico</span><p className="text-sm text-gold-bright">{kind==='races'?raceBenefitText(draft):lineageBenefitText(draft)}</p><p className="text-[11px] text-parchment-dim mt-1">Gerado automaticamente pelas regras do sistema. Não faz parte do texto editável da descrição.</p></div><button className={btn} onClick={save} disabled={saving}><Save className="w-4 h-4"/>{saving?'Salvando...':'Salvar alterações'}</button></div></div>:<div className="border border-gold-dim rounded-xl p-6 text-parchment-dim">Selecione {kind==='races'?'uma raça':'uma linhagem'} para editar.</div>}</div></section>
}
