import { useCallback, useEffect, useMemo, useState } from 'react';
import { LogOut, Users, ScrollText, MessageSquare, Lightbulb, Save, X, Pencil, Trash2, Plus, RefreshCw, GitBranch } from 'lucide-react';
import { supabase, type Character, type Player, type Suggestion } from '@/lib/supabase';
import CharacterCreation, { ATTRIBUTE_GROUPS, SKILL_GROUPS, RACES, GENDER_OPTIONS } from '@/components/CharacterCreation';
import AncestryAdmin from '@/components/AncestryAdmin';
import ClassTreeAdmin from '@/components/ClassTreeAdmin';

type Props={player:Player;onLogout:()=>void};
type Tab='characters'|'players'|'messages'|'suggestions'|'races'|'lineages'|'classes';
type SuggestionAdmin=Suggestion&{status?:'nova'|'lida'|'resolvida'};
const stage=(n:number)=>n<=4?'Aprendiz':n<=8?'Competente':n<=12?'Experiente':n<=16?'Especialista':'Mestre';
const input='w-full bg-shadow/60 border border-gold-dim rounded-lg px-3 py-2 text-parchment text-sm focus:outline-none focus:border-gold';
const btn='inline-flex items-center gap-2 px-3 py-2 rounded-lg border border-gold-dim text-gold hover:border-gold text-sm';
const labels:Record<string,string>={name:'Nome',nickname:'Apelido',age:'Idade',gender:'Gênero/Pronomes',race:'Raça',lineage:'Linhagem',height:'Altura',weight:'Peso',appearance:'Aparência',distinctive_marks:'Marcas distintivas',origin:'Origem',previous_occupation:'Ocupação anterior',personality:'Personalidade',ideals:'Ideais / Convicções',motivation:'Motivação',important_bond:'Vínculo importante',brief_history:'História breve',additional_characteristics:'Características adicionais',level:'Nível',class_name:'Classe',specialization:'Especialização',current_hp:'PV atual',current_mp:'PM atual',status:'Status'};
const textKeys=['name','nickname','height','weight','appearance','distinctive_marks','origin','previous_occupation','personality','ideals','motivation','important_bond','brief_history','additional_characteristics'] as const;

export default function MasterPage({player,onLogout}:Props){
 const [relations,setRelations]=useState<Record<string,any[]>>({});
 const [tab,setTab]=useState<Tab>('characters'); const [players,setPlayers]=useState<Player[]>([]); const [characters,setCharacters]=useState<Character[]>([]); const [suggestions,setSuggestions]=useState<SuggestionAdmin[]>([]); const [messages,setMessages]=useState<any[]>([]); const [selected,setSelected]=useState<Character|null>(null); const [draft,setDraft]=useState<Character|null>(null); const [editing,setEditing]=useState(false); const [saving,setSaving]=useState(false); const [messagePlayer,setMessagePlayer]=useState(''); const [messageText,setMessageText]=useState(''); const [creatingFor,setCreatingFor]=useState<Player|null>(null);
 const load=useCallback(async()=>{const [p,c,s,m]=await Promise.all([supabase.from('players').select('*').order('player_identifier'),supabase.from('characters').select('*').order('created_at'),supabase.from('suggestions').select('*').order('created_at',{ascending:false}),supabase.from('master_messages').select('*').order('created_at',{ascending:false})]);setPlayers((p.data||[]) as Player[]);setCharacters((c.data||[]) as Character[]);setSuggestions((s.data||[]) as SuggestionAdmin[]);setMessages(m.data||[])},[]);
 useEffect(()=>{load()},[load]);
 const playerMap=useMemo(()=>Object.fromEntries(players.map(p=>[p.id,p])),[players]);
 const classOptions=useMemo(()=>Array.from(new Set(characters.map(c=>c.class_name).filter(Boolean))) as string[],[characters]);
 const specializationOptions=useMemo(()=>Array.from(new Set(characters.map(c=>c.specialization).filter(Boolean))) as string[],[characters]);
 const loadRelations=async(id:string)=>{const tables=['character_items','character_conditions','character_effects','character_contacts','character_factions','character_reputations','character_objectives','character_events','character_diary'];const rr=await Promise.all(tables.map(t=>supabase.from(t).select('*').eq('character_id',id).order('created_at')));setRelations(Object.fromEntries(tables.map((t,i)=>[t,rr[i].data||[]])))};
 const openChar=(c:Character)=>{setSelected(c);setDraft(structuredClone(c));setEditing(false);loadRelations(c.id)};
 const deleteCharacter=async()=>{if(!selected)return;const owner=playerMap[selected.player_id];const ok=confirm(`Excluir permanentemente ${selected.name}?\n\nJogador: ${owner?.player_name||owner?.alcunha||'—'}\nInventário, diário, condições e demais registros vinculados também serão excluídos. Esta ação não pode ser desfeita.`);if(!ok)return;const {data,error}=await supabase.from('characters').delete().eq('id',selected.id).select('id');if(error){alert(`Não foi possível excluir o personagem: ${error.message}`);return}if(!data?.length){alert('O Supabase não excluiu o personagem. Execute a migration de permissões de exclusão incluída nesta versão.');return}setSelected(null);setDraft(null);setEditing(false);await load()};
 const addRelated=async(table:string)=>{if(!selected)return;let row:any={character_id:selected.id};if(table==='character_items'){const name=prompt('Nome do item:');if(!name)return;row={...row,name,type:prompt('Tipo:','comum')||'comum',quantity:Number(prompt('Quantidade:','1'))||1,equipped:confirm('Está equipado?'),description:prompt('Descrição:')||null}}else if(table==='character_conditions'){const condition=prompt('Condição:');if(!condition)return;row={...row,condition,intensity:Number(prompt('Intensidade (opcional):',''))||null,duration:prompt('Duração:')||null,notes:prompt('Observações:')||null}}else if(table==='character_effects'){const name=prompt('Nome do efeito:');if(!name)return;row={...row,name,description:prompt('Descrição:')||null,duration:prompt('Duração:')||null}}else if(table==='character_diary'){const title=prompt('Título:');if(!title)return;const content=prompt('Conteúdo:');if(!content)return;row={...row,title,content,session_reference:prompt('Data/Sessão:')||null}}else{const cfg:any={character_contacts:['name','Nome do contato'],character_factions:['faction_name','Nome da facção'],character_reputations:['group_or_place','Grupo ou lugar'],character_objectives:['objective','Objetivo'],character_events:['title','Título']}[table];const val=prompt(cfg[1]+':');if(!val)return;row[cfg[0]]=val;if(table==='character_events')row.description=prompt('Descrição:')||null;else row.notes=prompt('Observações:')||null;if(table==='character_objectives')row.status='active'}const {error}=await supabase.from(table).insert(row);if(error)alert(error.message);await loadRelations(selected.id)};
 const editRelated=async(table:string,r:any)=>{if(!selected)return;let patch:any={};if(table==='character_items'){const name=prompt('Nome:',r.name);if(!name)return;patch={name,quantity:Number(prompt('Quantidade:',String(r.quantity)))||0,equipped:confirm('Marcar como equipado?'),description:prompt('Descrição:',r.description||'')||null}}else if(table==='character_conditions'){const condition=prompt('Condição:',r.condition);if(!condition)return;patch={condition,intensity:Number(prompt('Intensidade:',String(r.intensity||'')))||null,duration:prompt('Duração:',r.duration||'')||null,notes:prompt('Observações:',r.notes||'')||null}}else if(table==='character_effects'){const name=prompt('Nome:',r.name);if(!name)return;patch={name,description:prompt('Descrição:',r.description||'')||null,duration:prompt('Duração:',r.duration||'')||null}}else if(table==='character_diary'){const title=prompt('Título:',r.title);if(!title)return;const content=prompt('Conteúdo:',r.content);if(content===null)return;patch={title,content,session_reference:prompt('Data/Sessão:',r.session_reference||'')||null,updated_at:new Date().toISOString()}}else{const cfg:any={character_contacts:['name','Nome'],character_factions:['faction_name','Facção'],character_reputations:['group_or_place','Grupo/Lugar'],character_objectives:['objective','Objetivo'],character_events:['title','Título']}[table];const val=prompt(cfg[1]+':',r[cfg[0]]);if(!val)return;patch[cfg[0]]=val;if(table==='character_events')patch.description=prompt('Descrição:',r.description||'')||null;else patch.notes=prompt('Observações:',r.notes||'')||null}const {error}=await supabase.from(table).update(patch).eq('id',r.id);if(error)alert(error.message);await loadRelations(selected.id)};
 const deleteRelated=async(table:string,id:string)=>{if(!selected||!confirm('Excluir este registro?'))return;const {error}=await supabase.from(table).delete().eq('id',id);if(error)alert(error.message);await loadRelations(selected.id)};
 const saveChar=async()=>{if(!draft)return;setSaving(true);const patch:any={};for(const k of textKeys)patch[k]=(draft as any)[k]||null;Object.assign(patch,{name:draft.name,gender:draft.gender||null,race:draft.race,lineage:draft.lineage,class_name:draft.class_name||null,specialization:draft.specialization||null,age:Number(draft.age)||0,level:Math.max(1,Math.min(20,Number(draft.level)||1)),current_hp:draft.current_hp,current_mp:draft.current_mp,status:draft.status,attributes:draft.attributes,skills:draft.skills});const {data,error}=await supabase.from('characters').update(patch).eq('id',draft.id).select().single();if(error)alert(error.message);else if(data){setSelected(data as Character);setDraft(structuredClone(data as Character));setCharacters(xs=>xs.map(x=>x.id===data.id?data as Character:x));setEditing(false)}setSaving(false)};
 const patchPlayer=async(id:string,patch:Partial<Player>)=>{const {error}=await supabase.from('players').update(patch).eq('id',id);if(error)alert(error.message);await load()};
 const sendMessage=async()=>{if(!messagePlayer||!messageText.trim())return;const {error}=await supabase.from('master_messages').insert({player_id:messagePlayer,content:messageText.trim()});if(error)alert(error.message);else{setMessageText('');await load()}};
 const deleteMessage=async(id:string)=>{if(!confirm('Excluir este recado? O jogador deixará de vê-lo imediatamente.'))return;const {error}=await supabase.from('master_messages').delete().eq('id',id);if(error){alert(`Não foi possível excluir o recado: ${error.message}`);return}await load()};
 const suggestionStatus=async(id:string,status:string)=>{const {error}=await supabase.from('suggestions').update({status}).eq('id',id);if(error)alert(error.message);await load()};
 const deleteSuggestion=async(id:string)=>{if(!confirm('Excluir esta sugestão?'))return;await supabase.from('suggestions').delete().eq('id',id);await load()};
 const updateAttr=(key:string,n:number)=>draft&&setDraft({...draft,attributes:{...draft.attributes,[key]:Math.max(0,Math.min(5,n))}});
 const updateSkill=(key:string,n:number)=>draft&&setDraft({...draft,skills:{...draft.skills,[key]:Math.max(0,Math.min(5,n))}});
 return <div className="min-h-screen bg-gradient-fantasy text-parchment"><header className="border-b border-gold-dim bg-shadow/70 sticky top-0 z-30"><div className="max-w-7xl mx-auto p-4 flex justify-between items-center"><div><h1 className="font-display text-2xl text-gold-bright">Painel do Mestre</h1><p className="text-xs text-parchment-dim">{player.player_name} · acesso administrativo</p></div><div className="flex gap-2"><button onClick={load} className={btn}><RefreshCw className="w-4 h-4"/>Atualizar</button><button onClick={onLogout} className={btn}><LogOut className="w-4 h-4"/>Sair</button></div></div></header><main className="max-w-7xl mx-auto p-4 md:p-6"><nav className="flex flex-wrap gap-2 mb-6">{([['characters','Personagens',ScrollText],['players','Jogadores',Users],['races','Raças',ScrollText],['lineages','Linhagens',ScrollText],['classes','Classes',GitBranch],['messages','Recados',MessageSquare],['suggestions','Sugestões',Lightbulb]] as const).map(([k,l,I])=><button key={k} onClick={()=>setTab(k)} className={`${btn} ${tab===k?'bg-gold/15 border-gold':''}`}><I className="w-4 h-4"/>{l}</button>)}</nav>
 {tab==='characters'&&<section><div className="flex flex-wrap items-center justify-between gap-3 mb-4"><div><h2 className="font-display text-xl text-gold-bright">Personagens</h2><p className="text-xs text-parchment-dim">Crie, consulte e administre as fichas de todos os jogadores.</p></div><select className={`${input} max-w-xs`} value="" onChange={e=>{const p=players.find(x=>x.id===e.target.value);if(p)setCreatingFor(p)}}><option value="">+ Criar personagem para...</option>{players.filter(p=>p.player_identifier!=='Mestre').map(p=><option key={p.id} value={p.id}>{p.player_name||p.alcunha}</option>)}</select></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{characters.map(c=>{const p=playerMap[c.player_id];return <button key={c.id} onClick={()=>openChar(c)} className="text-left bg-gradient-card border border-gold-dim rounded-xl p-4 hover:border-gold"><div className="flex gap-3">{c.thumbnail_url?<img src={c.thumbnail_url} className="w-16 h-16 rounded-lg object-cover border border-gold-dim"/>:<div className="w-16 h-16 rounded-lg bg-shadow border border-gold-dim flex items-center justify-center text-gold">{c.name[0]}</div>}<div><h3 className="font-display text-lg text-gold-bright">{c.name}</h3><p className="text-sm">Jogador: {p?.player_name||p?.alcunha||'—'}</p><p className="text-xs text-gold">Nível {c.level} · {stage(c.level)} · {c.status==='morto'?'Morto':c.status==='desaparecido'?'Desaparecido':'Vivo'}</p><p className="text-xs text-parchment-dim">Classe: {c.class_name||'—'}</p></div></div></button>})}</div></section>}
 {tab==='players'&&<section className="space-y-3">{players.map(p=><div key={p.id} className="bg-gradient-card border border-gold-dim rounded-xl p-4 grid md:grid-cols-[1fr_auto_auto] gap-3 items-center"><div><b className="text-gold-bright">{p.player_name||'Sem jogador'}</b><p className="text-sm text-parchment-dim">{p.alcunha} · {p.player_identifier||'Sem ID'} · {p.status}</p></div><label className="flex gap-2 items-center text-sm"><input type="checkbox" checked={!!p.character_creation_allowed} onChange={e=>patchPlayer(p.id,{character_creation_allowed:e.target.checked})}/>Liberar personagem adicional</label><select className={input} value={p.status} onChange={e=>patchPlayer(p.id,{status:e.target.value as Player['status']})}><option value="ativa">Ativa</option><option value="espera">Em espera</option></select></div>)}</section>}
 {tab==='races'&&<AncestryAdmin kind="races"/>}
 {tab==='lineages'&&<AncestryAdmin kind="lineages"/>}
 {tab==='classes'&&<ClassTreeAdmin characters={characters} players={players}/>}
 {tab==='messages'&&<section className="grid lg:grid-cols-[.8fr_1.2fr] gap-5"><div className="bg-gradient-card border border-gold-dim rounded-xl p-5"><h2 className="font-display text-gold-bright mb-4">Enviar recado</h2><select className={`${input} mb-3`} value={messagePlayer} onChange={e=>setMessagePlayer(e.target.value)}><option value="">Escolha o jogador</option>{players.filter(p=>p.player_identifier!=='Mestre').map(p=><option key={p.id} value={p.id}>{p.player_name||p.alcunha}</option>)}</select><textarea className={input} rows={6} value={messageText} onChange={e=>setMessageText(e.target.value)} placeholder="Recado do Mestre..."/><button className={`${btn} mt-3`} onClick={sendMessage}><Plus className="w-4 h-4"/>Enviar</button></div><div><h2 className="font-display text-gold-bright mb-4">Recados enviados</h2><div className="space-y-3">{messages.map(m=><div key={m.id} className="bg-gradient-card border border-gold-dim rounded-xl p-4"><div className="flex justify-between gap-3 items-start"><b className="text-gold">Para: {playerMap[m.player_id]?.player_name||'—'}</b><button onClick={()=>deleteMessage(m.id)} className={`${btn} text-red-300 border-red-900/70 hover:border-red-500`} title="Excluir recado"><Trash2 className="w-4 h-4"/>Excluir</button></div><p className="mt-2 whitespace-pre-wrap">{m.content}</p><p className="text-xs text-parchment-dim mt-2">{new Date(m.created_at).toLocaleString('pt-BR')}</p></div>)}</div></div></section>}
 {tab==='suggestions'&&<section><h2 className="font-display text-gold-bright mb-4">Sugestões recebidas</h2><div className="space-y-3">{suggestions.length===0?<p className="text-parchment-dim">Nenhuma sugestão recebida.</p>:suggestions.map(s=><div key={s.id} className="bg-gradient-card border border-gold-dim rounded-xl p-4"><div className="flex flex-wrap justify-between gap-3"><div><b className="text-gold">{playerMap[s.player_id]?.player_name||playerMap[s.player_id]?.alcunha||'Jogador'}</b><p className="text-xs text-parchment-dim">{new Date(s.created_at).toLocaleString('pt-BR')}</p></div><div className="flex gap-2"><select className={input} value={s.status||'nova'} onChange={e=>suggestionStatus(s.id,e.target.value)}><option value="nova">Nova</option><option value="lida">Lida</option><option value="resolvida">Resolvida</option></select><button onClick={()=>deleteSuggestion(s.id)} className={btn}><Trash2 className="w-4 h-4"/></button></div></div><p className="mt-3 whitespace-pre-wrap">{s.content}</p></div>)}</div></section>}
 </main>
 {creatingFor&&<div className="fixed inset-0 z-50 bg-black/80 overflow-y-auto"><div className="min-h-screen"><div className="sticky top-0 z-50 bg-stone border-b border-gold-dim px-4 py-3 flex justify-between items-center"><div><b className="font-display text-gold-bright">Criando personagem como Mestre</b><p className="text-xs text-parchment-dim">Ficha destinada a {creatingFor.player_name||creatingFor.alcunha}</p></div><button className={btn} onClick={()=>setCreatingFor(null)}><X className="w-4 h-4"/>Fechar</button></div><CharacterCreation player={creatingFor} consumeCharacterAllowance={false} onBack={()=>setCreatingFor(null)} onCreated={async()=>{setCreatingFor(null);await load()}}/></div></div>}
 {selected&&draft&&<div className="fixed inset-0 z-50 bg-black/75 p-3 md:p-6 overflow-y-auto"><div className="max-w-6xl mx-auto bg-stone border border-gold rounded-2xl shadow-2xl"><div className="sticky top-0 z-10 bg-stone border-b border-gold-dim p-4 flex justify-between gap-3"><div><h2 className="font-display text-2xl text-gold-bright">{selected.name}</h2><p className="text-xs text-parchment-dim">Modo Mestre · edição completa · {stage(draft.level)}</p></div><div className="flex gap-2">{!editing?<><button className={btn} onClick={()=>setEditing(true)}><Pencil className="w-4 h-4"/>Editar ficha</button><button className={`${btn} text-red-300 border-red-900/70 hover:border-red-500`} onClick={deleteCharacter}><Trash2 className="w-4 h-4"/>Excluir</button></>:<><button className={btn} onClick={()=>{setDraft(structuredClone(selected));setEditing(false)}}><X className="w-4 h-4"/>Cancelar</button><button className={btn} disabled={saving} onClick={saveChar}><Save className="w-4 h-4"/>{saving?'Salvando...':'Salvar'}</button></>}<button className={btn} onClick={()=>setSelected(null)}><X className="w-4 h-4"/></button></div></div><div className="p-5 space-y-8">
 <section><h3 className="font-display text-gold mb-3">Identidade, História & Progressão</h3><div className="grid md:grid-cols-3 gap-3">
{textKeys.map(k=><label key={k} className="text-xs text-gold">{labels[k]}{editing?(k==='appearance'||k==='brief_history'||k==='personality'?<textarea className={`${input} mt-1`} rows={3} value={(draft as any)[k]||''} onChange={e=>setDraft({...draft,[k]:e.target.value})}/>:<input className={`${input} mt-1`} value={(draft as any)[k]||''} onChange={e=>setDraft({...draft,[k]:e.target.value})}/>):<div className="text-sm text-parchment mt-1 whitespace-pre-wrap">{String((draft as any)[k]||'—')}</div>}</label>)}
<label className="text-xs text-gold">Gênero/Pronomes{editing?<select className={`${input} mt-1`} value={draft.gender||''} onChange={e=>setDraft({...draft,gender:e.target.value||null})}><option value="">Não informado</option>{GENDER_OPTIONS.map(g=><option key={g.id} value={g.id}>{g.label}</option>)}</select>:<div className="text-sm text-parchment mt-1">{GENDER_OPTIONS.find(g=>g.id===draft.gender)?.label||draft.gender||'—'}</div>}</label>
<label className="text-xs text-gold">Raça{editing?<select className={`${input} mt-1`} value={draft.race} onChange={e=>{const race=e.target.value;setDraft({...draft,race,lineage:RACES.find(r=>r.name===race)?.lineages[0]?.name||''})}}>{RACES.map(r=><option key={r.name} value={r.name}>{r.name}</option>)}</select>:<div className="text-sm text-parchment mt-1">{draft.race||'—'}</div>}</label>
<label className="text-xs text-gold">Linhagem{editing?<select className={`${input} mt-1`} value={draft.lineage} onChange={e=>setDraft({...draft,lineage:e.target.value})}>{(RACES.find(r=>r.name===draft.race)?.lineages||[]).map(l=><option key={l.name} value={l.name}>{l.name}</option>)}</select>:<div className="text-sm text-parchment mt-1">{draft.lineage||'—'}</div>}</label>
<label className="text-xs text-gold">Classe{editing?<select className={`${input} mt-1`} value={draft.class_name||''} onChange={e=>setDraft({...draft,class_name:e.target.value||null})}><option value="">— Sem classe —</option>{classOptions.map(x=><option key={x} value={x}>{x}</option>)}</select>:<div className="text-sm text-parchment mt-1">{draft.class_name||'—'}</div>}</label>
<label className="text-xs text-gold">Especialização{editing?<select className={`${input} mt-1`} value={draft.specialization||''} onChange={e=>setDraft({...draft,specialization:e.target.value||null})}><option value="">— Sem especialização —</option>{specializationOptions.map(x=><option key={x} value={x}>{x}</option>)}</select>:<div className="text-sm text-parchment mt-1">{draft.specialization||'—'}</div>}</label>
<label className="text-xs text-gold">Idade{editing?<input type="number" className={`${input} mt-1`} value={draft.age} onChange={e=>setDraft({...draft,age:Number(e.target.value)})}/>:<div className="text-sm text-parchment mt-1">{draft.age}</div>}</label><label className="text-xs text-gold">Nível{editing?<input type="number" min={1} max={20} className={`${input} mt-1`} value={draft.level} onChange={e=>setDraft({...draft,level:Number(e.target.value)})}/>:<div className="text-sm text-parchment mt-1">{draft.level} · {stage(draft.level)}</div>}</label><label className="text-xs text-gold">Status{editing?<select className={`${input} mt-1`} value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value as Character['status']})}><option value="vivo">Vivo</option><option value="morto">Morto</option><option value="desaparecido">Desaparecido</option></select>:<div className="text-sm text-parchment mt-1">{draft.status}</div>}</label><label className="text-xs text-gold">PV atual{editing?<input type="number" className={`${input} mt-1`} value={draft.current_hp??''} onChange={e=>setDraft({...draft,current_hp:e.target.value===''?null:Number(e.target.value)})}/>:<div className="text-sm text-parchment mt-1">{draft.current_hp??'—'}</div>}</label><label className="text-xs text-gold">PM atual{editing?<input type="number" className={`${input} mt-1`} value={draft.current_mp??''} onChange={e=>setDraft({...draft,current_mp:e.target.value===''?null:Number(e.target.value)})}/>:<div className="text-sm text-parchment mt-1">{draft.current_mp??'—'}</div>}</label></div></section>
 <section><h3 className="font-display text-gold mb-3">Atributos</h3><div className="grid md:grid-cols-3 gap-4">{ATTRIBUTE_GROUPS.map(g=><div key={g.name} className="bg-shadow/40 border border-gold-dim rounded-xl p-4"><b className="text-gold-bright">{g.name}</b>{g.attributes.map(a=><div key={a.name} className="flex justify-between items-center mt-3"><span>{a.name}</span>{editing?<input type="number" min={0} max={5} className="w-16 bg-shadow border border-gold-dim rounded px-2 py-1" value={draft.attributes[a.name]??0} onChange={e=>updateAttr(a.name,Number(e.target.value))}/>:<b className="text-gold">{(draft.attributes[a.name]??0)+(draft.racial_attribute_bonus?.[a.name]??0)}{(draft.racial_attribute_bonus?.[a.name]??0)>0&&<small className="ml-1 text-parchment-dim">({draft.attributes[a.name]??0} +1 racial)</small>}</b>}</div>)}</div>)}</div></section>
 <section><h3 className="font-display text-gold mb-3">Habilidades</h3><div className="grid md:grid-cols-2 xl:grid-cols-4 gap-4">{SKILL_GROUPS.map(g=><div key={g.name} className="bg-shadow/40 border border-gold-dim rounded-xl p-4"><b className="text-gold-bright">{g.name}</b>{g.skills.map(sk=><div key={sk.name} className="flex justify-between items-center mt-2 text-sm"><span>{sk.name}</span>{editing?<input type="number" min={0} max={5} className="w-14 bg-shadow border border-gold-dim rounded px-2 py-1" value={draft.skills[sk.name]??0} onChange={e=>updateSkill(sk.name,Number(e.target.value))}/>:<b className="text-gold">{(draft.skills[sk.name]??0)+(draft.lineage_skill_bonuses?.[sk.name]??0)}{(draft.lineage_skill_bonuses?.[sk.name]??0)>0&&<small className="ml-1 text-parchment-dim">({draft.skills[sk.name]??0} +1 linhagem)</small>}</b>}</div>)}</div>)}</div></section>
 <section><h3 className="font-display text-gold mb-3">Inventário, Condições, Jornada & Diário</h3><div className="grid md:grid-cols-2 gap-4">{([['character_items','Inventário'],['character_conditions','Condições'],['character_effects','Efeitos'],['character_contacts','Aliados & Contatos'],['character_factions','Facções'],['character_reputations','Reputações'],['character_objectives','Objetivos'],['character_events','Acontecimentos'],['character_diary','Diário']] as const).map(([table,title])=><div key={table} className="bg-shadow/40 border border-gold-dim rounded-xl p-4"><div className="flex justify-between items-center mb-3"><b className="text-gold-bright">{title}</b><button className={btn} onClick={()=>addRelated(table)}><Plus className="w-4 h-4"/>Adicionar</button></div><div className="space-y-2">{(relations[table]||[]).length===0?<p className="text-xs text-parchment-dim">Nenhum registro.</p>:(relations[table]||[]).map((r:any)=><div key={r.id} className="border border-gold-dim/60 rounded-lg p-3 flex justify-between gap-3"><div className="min-w-0"><b className="text-sm">{r.name||r.condition||r.faction_name||r.group_or_place||r.objective||r.title||'Registro'}</b><p className="text-xs text-parchment-dim truncate">{r.description||r.notes||r.content||r.duration||r.type||'—'}</p></div><div className="flex gap-2 shrink-0"><button onClick={()=>editRelated(table,r)}><Pencil className="w-4 h-4 text-gold"/></button><button onClick={()=>deleteRelated(table,r.id)}><Trash2 className="w-4 h-4 text-parchment-dim"/></button></div></div>)}</div></div>)}</div></section>
 </div></div></div>}
 </div>
}
