import { useState, useEffect, useCallback, useMemo, useRef } from 'react';
import { createPortal } from 'react-dom';
import { LogOut, Scroll, MessageSquare, Lightbulb, Plus, User, Send, Loader2, Save, X, Lock, Info, Shield, Gauge, Sword, Backpack, BookOpen, Users, Target, Trash2, Pencil, ImagePlus, Check, Ban } from 'lucide-react';
import { supabase, type Player, type PersonalNote, type MasterMessage, type Character, type ClassNode, type WeaponPublic } from '@/lib/supabase';
import { ATTRIBUTE_GROUPS, SKILL_GROUPS } from '@/components/CharacterCreation';
import { renderCharacterText } from '@/lib/characterLanguage';
import { attributeChoices, type RaceDefinition } from '@/lib/ancestry';
import { classUnlockCount } from '@/lib/classUnlocks';
import ClassDiscoveryTree from '@/components/ClassDiscoveryTree';

type PlayerPageProps = { player: Player; onLogout: () => void; onCreateCharacter: () => void; };
type Tab = 'ficha'|'combate'|'inventario'|'historia'|'jornada'|'diario'|'classes'|'regras';
type DiaryEntry={id:string;character_id:string;title:string;content:string;session_reference:string|null;created_at:string;updated_at:string};
type Item={id:string;character_id?:string;name:string;type:string;quantity:number;equipped:boolean;description:string|null;properties:Record<string,unknown>;weapon_id?:string|null};
type Condition={id:string;condition:string;intensity:number|null;notes:string|null;duration:string|null};
type Effect={id:string;name:string;description:string|null;duration:string|null;modifiers:Record<string,unknown>};
type Contact={id:string;name:string;relationship:string|null;notes:string|null};
type Faction={id:string;faction_name:string;relationship:string|null;notes:string|null};
type Reputation={id:string;group_or_place:string;reputation:string|null;notes:string|null};
type Objective={id:string;objective:string;notes:string|null;status:string};
type Event={id:string;title:string;description:string|null;session_reference:string|null};

const stageForLevel=(level:number)=>level<=4?'Aprendiz':level<=8?'Competente':level<=12?'Experiente':level<=16?'Especialista':'Mestre';
const statusLabel=(x:Character['status']|undefined)=>x==='morto'?'Morto':x==='desaparecido'?'Desaparecido':'Vivo';
const v=(c:Character,key:string)=>(c.attributes?.[key]??0)+(c.racial_attribute_bonus?.[key]??0);
const s=(c:Character,key:string)=>(c.skills?.[key]??0)+(c.lineage_skill_bonuses?.[key]??0);
const maxHp=(c:Character)=>15+v(c,'Vigor')*5+(c.level-1)*2;
const maxMp=(c:Character)=>{const mental=Math.max(...['Inteligência','Raciocínio','Sabedoria','Percepção'].map(k=>v(c,k)));const mystical=Math.max(...['Elementalismo','Arcanismo','Ritualismo','Manipulação Arcana','Teologia','Espiritualismo'].map(k=>s(c,k)));return mystical>0?5+mental*2+mystical*2+c.level:0};
const movement=(c:Character)=>6+Math.max(1,Math.floor((v(c,'Agilidade')+s(c,'Atletismo'))/2));
const genderLabel=(g:string|null)=>({ele:'Ele / Dele',ela:'Ela / Dela',elu:'Elu / Delu',neutro:'Não faz diferença'}[g||'']||g||'—');
const field='w-full bg-shadow/60 border border-gold-dim rounded-lg px-3 py-2 text-parchment text-sm';

function Tip({children}:{children:React.ReactNode}){
  const ref=useRef<HTMLSpanElement>(null); const [pos,setPos]=useState<{left:number;top:number}|null>(null);
  const show=()=>{const r=ref.current?.getBoundingClientRect();if(r)setPos({left:Math.min(window.innerWidth-160,Math.max(160,r.left+r.width/2)),top:Math.max(12,r.top-8)})};
  return <span ref={ref} className="inline-flex ml-1 align-middle" onMouseEnter={show} onMouseLeave={()=>setPos(null)} onFocus={show} onBlur={()=>setPos(null)} tabIndex={0}><Info className="w-3.5 h-3.5 text-gold/70 cursor-help"/>{pos&&createPortal(<span className="pointer-events-none fixed z-[9999] -translate-x-1/2 -translate-y-full w-72 max-w-[80vw] bg-stone border border-gold-dim rounded-lg p-3 shadow-gold text-xs text-parchment-dim font-body leading-relaxed" style={{left:pos.left,top:pos.top}}>{children}</span>,document.body)}</span>;
}
function Dots({base,bonus=0,max=5,bonusTitle}:{base:number;bonus?:number;max?:number;bonusTitle?:string}){const total=base+bonus;const visibleMax=Math.max(max,total);return <span className="trilha-dots inline-flex gap-1.5">{Array.from({length:visibleMax},(_,i)=>{const isFilled=i<total;const isBonus=i>=base&&i<total&&bonus>0;return <span key={i} title={isBonus?bonusTitle:undefined} className={`trilha-dot ${isFilled?'is-filled':''} ${isBonus?'is-bonus':''}`}/>})}</span>}
function Empty({children='Nenhum registro.'}:{children?:React.ReactNode}){return <p className="text-parchment-dim/60 text-sm font-body py-3">{children}</p>}

function RulesPanel({playerName}:{playerName:string}){
  const card='bg-shadow/40 border border-gold-dim rounded-xl p-4 sm:p-5';
  const title='font-display text-lg text-gold-bright mb-3';
  return <div className="max-w-4xl mx-auto space-y-5 pb-10">
    <div className="flex items-end justify-between gap-4 border-b border-gold-dim pb-4">
      <div><p className="text-xs uppercase tracking-[0.25em] text-gold/70">Consulta rápida</p><h2 className="font-display text-2xl sm:text-3xl text-gold-bright mt-1">Regras do TRILHA</h2></div>
      <span className="hidden sm:block text-xs text-parchment-dim">Trajetória · Roleplay · Identidade · Liberdade · História · Aventura</span>
    </div>

    <section className={card}><h3 className={title}>🎲 Testes</h3><p className="text-sm text-parchment-dim">Quando uma ação tiver resultado incerto, o Mestre pode pedir um <b className="text-parchment">Teste</b>.</p><div className="my-3 rounded-lg border border-gold-dim bg-stone/50 px-4 py-3 text-center font-display text-gold">Atributo + Habilidade = quantidade de d10</div><p className="text-sm text-parchment-dim">Cada resultado <b className="text-parchment">maior que a Dificuldade</b> conta como 1 sucesso. <b className="text-parchment">1</b> anula um sucesso. <b className="text-parchment">10</b> conta como 1 sucesso e permite rolar +1d10; outro 10 explode novamente.</p><div className="overflow-x-auto mt-4"><table className="w-full text-sm"><thead><tr className="text-left text-gold border-b border-gold-dim"><th className="py-2 pr-4">Sucessos finais</th><th className="py-2">Resultado</th></tr></thead><tbody className="text-parchment-dim">{[['−1 ou menos','Falha Crítica'],['0','Falha'],['1','Marginal'],['2','Moderado'],['3','Completo'],['4','Excepcional'],['5+','Fenomenal']].map(([a,b])=><tr key={a} className="border-b border-gold-dim/40"><td className="py-2 pr-4 font-display text-gold-bright">{a}</td><td>{b}</td></tr>)}</tbody></table></div></section>

    <div className="grid md:grid-cols-2 gap-5"><section className={card}><h3 className={title}>❤️ Pontos de Vida (PV)</h3><p className="text-sm text-parchment-dim">Representam a condição física do personagem.</p><p className="my-3 text-sm text-gold">PV Máximo = 15 + (Vigor × 5) + ((Nível − 1) × 2)</p><p className="text-sm text-parchment-dim">Ao chegar a <b className="text-parchment">0 PV</b>, o personagem fica <b className="text-parchment">Inconsciente</b>.</p></section><section className={card}><h3 className={title}>✦ Pontos de Mana (PM)</h3><p className="text-sm text-parchment-dim">Representam a energia usada em magias e efeitos sobrenaturais.</p><p className="my-3 text-sm text-gold">PM Máximo = 5 + (Maior Mental × 2) + (Maior Mística × 2) + Nível</p><p className="text-sm text-parchment-dim">Em <b className="text-parchment">0 PM</b>, o personagem não pode utilizar magias até recuperar Mana.</p></section></div>

    <section className={card}><h3 className={title}>💤 Descanso e Recuperação</h3><div className="grid sm:grid-cols-2 gap-4 text-sm"><div><b className="text-gold">Descanso Curto</b><p className="text-parchment-dim mt-1">PV: Vigor × 2<br/>PM: maior Atributo Mental × 2</p></div><div><b className="text-gold">Descanso Longo</b><p className="text-parchment-dim mt-1">Recupera todos os PV e PM.</p></div></div><p className="text-xs text-parchment-dim mt-4 border-t border-gold-dim/50 pt-3">PV e PM também podem ser recuperados por poções, pergaminhos, alimentos, magias e outros recursos. Certos ferimentos, condições e efeitos mágicos podem persistir mesmo após um Descanso Longo.</p></section>

    <section className={card}><h3 className={title}>⚔️ Combate</h3><div className="space-y-4 text-sm text-parchment-dim"><div><b className="text-gold">Iniciativa</b><p>Percepção + Vigilância. A maior age primeiro; em empate, vence a maior Percepção.</p></div><div><b className="text-gold">Turno</b><p>1 Ação + 1 Movimento. O Movimento pode ser dividido antes e depois da Ação. A Ação pode atacar, conjurar, usar habilidade/item, interagir ou realizar um segundo Movimento.</p></div><div><b className="text-gold">Reação Defensiva</b><p>1 reação para Evasão ou Bloqueio. Depois de usada, retorna quando chega novamente o turno do personagem. Sem reação disponível, usa-se a Defesa Passiva.</p></div><div className="grid sm:grid-cols-3 gap-3"><div className="bg-stone/40 rounded-lg p-3"><b className="text-parchment">Evasão</b><br/>Agilidade + Defesa</div><div className="bg-stone/40 rounded-lg p-3"><b className="text-parchment">Bloqueio</b><br/>Força + Defesa</div><div className="bg-stone/40 rounded-lg p-3"><b className="text-parchment">Defesa Passiva</b><br/>⌊Defesa ÷ 2⌋ sucessos automáticos</div></div><div><b className="text-gold">Ataque × Defesa</b><p>É um Teste Oposto. O ataque precisa superar os sucessos da defesa; <b className="text-parchment">empates favorecem o defensor</b>. Sucessos excedentes do atacante aumentam o dano.</p></div><div><b className="text-gold">Dano</b><p>Dano Bruto = Dano Base + Sucessos Excedentes. Dano Final = Dano Bruto − Armadura. Um ataque que acerta causa no mínimo 1 PV.</p></div></div></section>

    <div className="grid md:grid-cols-2 gap-5"><section className={card}><h3 className={title}>🛡️ Armaduras</h3><div className="space-y-2 text-sm text-parchment-dim"><p><b className="text-parchment">Leve:</b> Absorção 1, sem penalidade.</p><p><b className="text-parchment">Média:</b> Absorção 2; −1 dado em mobilidade ligada à Agilidade, quedas e natação; −1 m de Movimento.</p><p><b className="text-parchment">Pesada:</b> Absorção 3; −2 dados nesses testes; −2 m de Movimento.</p></div></section><section className={card}><h3 className={title}>🤝 Ajudar</h3><p className="text-sm text-parchment-dim">Gaste sua <b className="text-parchment">Ação</b> para conceder <b className="text-parchment">+1 sucesso automático</b> ao teste de um aliado. Descreva a ajuda e relacione-a a um de seus próprios Atributos ou Habilidades. Um teste recebe no máximo +1 sucesso por Ajudar.</p></section></div>

    <section className={card}><h3 className={title}>⚠️ Condições</h3><p className="text-sm text-parchment-dim">Personagens podem ser afetados por Condições, como Caído, Atordoado, Envenenado, Agarrado ou Inconsciente. Cada Condição possui efeitos e duração próprios, apresentados quando ela for aplicada.</p></section>

    <section className={card}><h3 className={title}>⭐ Progressão</h3><div className="grid grid-cols-2 sm:grid-cols-5 gap-2 text-center text-sm">{[['1–4','Aprendiz'],['5–8','Competente'],['9–12','Experiente'],['13–16','Especialista'],['17–20','Mestre']].map(([lv,st])=><div key={lv} className="bg-stone/40 rounded-lg p-3"><div className="text-gold-bright font-display">{lv}</div><div className="text-parchment-dim text-xs mt-1">{st}</div></div>)}</div><p className="text-sm text-parchment-dim mt-4">O personagem começa como <b className="text-parchment">Aprendiz</b>, sem Classe definida. Conforme evolui seus Atributos, Habilidades e experiências, novos caminhos podem ser revelados. <b className="text-parchment">As Classes não são escolhidas no início: são descobertas durante a progressão.</b></p></section>

    <section className={card}><h3 className={title}>🧩 Atributos e Habilidades</h3><p className="text-sm text-parchment-dim">Atributos representam capacidades do personagem; Habilidades representam aquilo que aprendeu ou treinou. O Mestre combina o Atributo + Habilidade adequados à ação. A combinação pode mudar conforme a forma como a ação é realizada.</p></section>

    <section className={card}><h3 className={title}>🎭 Interpretação e Decisões</h3><p className="text-sm text-parchment-dim"><b className="text-parchment">Nem toda ação exige um Teste.</b> Sem risco, oposição ou incerteza relevante, a ação pode simplesmente acontecer. Quando uma rolagem for necessária, o Mestre determina a Dificuldade e a combinação adequada. As regras orientam a aventura; a descrição e as escolhas do jogador também fazem parte da resolução.</p></section>

    <section className="mt-12 rounded-2xl border border-gold-dim bg-gradient-card p-6 sm:p-10 text-center shadow-gold">
      <p className="text-sm text-parchment-dim">Olá,</p><h2 className="font-display text-3xl text-gold-bright mt-1">{playerName}.</h2><div className="w-20 h-px bg-gold-dim mx-auto my-6"/><h3 className="font-display text-4xl sm:text-5xl text-gold-bright tracking-wider">TRILHA</h3><p className="text-xs sm:text-sm uppercase tracking-[0.18em] text-gold mt-2">Trajetória · Roleplay · Identidade · Liberdade · História · Aventura</p><div className="max-w-2xl mx-auto mt-7 space-y-4 text-sm sm:text-base leading-relaxed text-parchment-dim text-left"><p>Este sistema nasceu como uma adaptação e uma homenagem aos muitos sistemas de RPG que vieram antes dele. O TRILHA foi pensado para facilitar o aprendizado das regras sem deixar que elas ocupem o lugar mais importante da mesa: <b className="text-parchment">a experiência dos jogadores, suas escolhas e o roleplay de seus personagens</b>.</p><p>Aqui, você não precisa decidir desde o início tudo aquilo que seu personagem será. Ele começa sua jornada como <b className="text-parchment">Aprendiz</b>, e são suas escolhas, experiências, atributos e habilidades que, pouco a pouco, revelam os caminhos que poderá seguir.</p><p>Algumas trilhas surgirão naturalmente. Outras dependerão das decisões tomadas durante a jornada. E algumas talvez nunca sejam descobertas.</p><p>As regras existem para dar estrutura à aventura, não para determinar como ela deve acontecer. <b className="text-parchment">Experimente, interprete, erre, arrisque e descubra quem seu personagem se tornará.</b></p></div><div className="w-20 h-px bg-gold-dim mx-auto my-7"/><p className="font-display text-lg sm:text-xl text-gold-bright italic">Ἡ ἀτραπὸς καθ᾽ ἕκαστον βῆμα πλάττεται.</p><p className="text-sm text-parchment-dim mt-2">“A trilha é forjada a cada passo.”</p>
    </section>
  </div>
}

export default function PlayerPage({player,onLogout,onCreateCharacter}:PlayerPageProps){
  const isMaster=player.player_identifier==='Mestre';
  const [characters,setCharacters]=useState<Character[]>([]),[charactersLoading,setCharactersLoading]=useState(true),[selectedCharacter,setSelectedCharacter]=useState<Character|null>(null),[tab,setTab]=useState<Tab>('ficha');
  const [notes,setNotes]=useState<PersonalNote[]>([]),[notesContent,setNotesContent]=useState(''),[notesLoading,setNotesLoading]=useState(false),[notesSaving,setNotesSaving]=useState(false),[notesSaved,setNotesSaved]=useState(false);
  const [masterMessages,setMasterMessages]=useState<MasterMessage[]>([]),[suggestionOpen,setSuggestionOpen]=useState(false),[suggestionText,setSuggestionText]=useState(''),[suggestionSending,setSuggestionSending]=useState(false),[suggestionSent,setSuggestionSent]=useState(false);
  const [items,setItems]=useState<Item[]>([]),[conditions,setConditions]=useState<Condition[]>([]),[effects,setEffects]=useState<Effect[]>([]),[contacts,setContacts]=useState<Contact[]>([]),[factions,setFactions]=useState<Faction[]>([]),[reputations,setReputations]=useState<Reputation[]>([]),[objectives,setObjectives]=useState<Objective[]>([]),[events,setEvents]=useState<Event[]>([]),[diary,setDiary]=useState<DiaryEntry[]>([]);
  const [diaryTitle,setDiaryTitle]=useState(''),[diaryContent,setDiaryContent]=useState(''),[diarySession,setDiarySession]=useState(''),[diarySaving,setDiarySaving]=useState(false);
  const [editingHistory,setEditingHistory]=useState(false),[historyDraft,setHistoryDraft]=useState<Record<string,string>>({}),[saving,setSaving]=useState(false),[uploading,setUploading]=useState(false);
  const [allPlayers,setAllPlayers]=useState<Player[]>([]),[allCharacters,setAllCharacters]=useState<Character[]>([]);
  const [ancestryRaces,setAncestryRaces]=useState<RaceDefinition[]>([]);
  const [classNodes,setClassNodes]=useState<ClassNode[]>([]);
  const [weaponCatalog,setWeaponCatalog]=useState<WeaponPublic[]>([]),[weaponChoice,setWeaponChoice]=useState(''),[weaponProficiency,setWeaponProficiency]=useState<Record<string,boolean>>({});
  const [legacyAttribute,setLegacyAttribute]=useState(''),[legacySkill1,setLegacySkill1]=useState(''),[legacySkill2,setLegacySkill2]=useState(''),[legacySaving,setLegacySaving]=useState(false);

  const loadCharacters=useCallback(async()=>{setCharactersLoading(true);const {data}=await supabase.from('characters').select('*').eq('player_id',player.id).order('created_at',{ascending:true});setCharacters((data||[]) as Character[]);setCharactersLoading(false)},[player.id]);
  const loadNotes=useCallback(async()=>{setNotesLoading(true);const {data}=await supabase.from('personal_notes').select('*').eq('player_id',player.id).order('updated_at',{ascending:false});setNotes(data||[]);if(data?.length)setNotesContent(data[0].content);setNotesLoading(false)},[player.id]);
  const loadMasterMessages=useCallback(async()=>{const {data}=await supabase.from('master_messages').select('*').eq('player_id',player.id).order('created_at',{ascending:false});setMasterMessages(data||[])},[player.id]);
  const loadMasterData=useCallback(async()=>{if(!isMaster)return;const [p,c]=await Promise.all([supabase.from('players').select('*').order('player_name'),supabase.from('characters').select('*').order('created_at')]);setAllPlayers((p.data||[]) as Player[]);setAllCharacters((c.data||[]) as Character[])},[isMaster]);
  useEffect(()=>{loadCharacters();loadNotes();loadMasterMessages();loadMasterData()},[loadCharacters,loadNotes,loadMasterMessages,loadMasterData]);
  useEffect(()=>{(async()=>{const [rr,ll]=await Promise.all([supabase.from('races').select('*').order('name'),supabase.from('lineages').select('*').order('name')]);if(rr.data){const lineages=(ll.data||[]) as any[];setAncestryRaces((rr.data as any[]).map(r=>({...r,lineages:lineages.filter(l=>l.race_id===r.id)})) as RaceDefinition[])}})()},[]);
  useEffect(()=>{(async()=>{const {data}=await supabase.from('class_nodes').select('*').order('sort_order');setClassNodes((data||[]) as ClassNode[])})()},[]);
  useEffect(()=>{(async()=>{const {data}=await supabase.from('weapon_catalog_public').select('*').order('family').order('name');setWeaponCatalog((data||[]) as WeaponPublic[])})()},[]);

  const loadRelations=useCallback(async(id:string)=>{const tables=['character_items','character_conditions','character_effects','character_contacts','character_factions','character_reputations','character_objectives','character_events','character_diary'] as const;const r=await Promise.all(tables.map(t=>supabase.from(t).select('*').eq('character_id',id).order('created_at',{ascending:true})));setItems((r[0].data||[]) as Item[]);setConditions((r[1].data||[]) as Condition[]);setEffects((r[2].data||[]) as Effect[]);setContacts((r[3].data||[]) as Contact[]);setFactions((r[4].data||[]) as Faction[]);setReputations((r[5].data||[]) as Reputation[]);setObjectives((r[6].data||[]) as Objective[]);setEvents((r[7].data||[]) as Event[]);setDiary((r[8].data||[]) as DiaryEntry[])},[]);
  const loadWeaponProficiency=useCallback(async(id:string)=>{const {data}=await supabase.rpc('get_character_weapon_proficiency',{p_character_id:id});const map:Record<string,boolean>={};((data||[]) as {weapon_id:string;is_proficient:boolean}[]).forEach(x=>map[x.weapon_id]=x.is_proficient);setWeaponProficiency(map)},[]);
  useEffect(()=>{if(selectedCharacter){loadRelations(selectedCharacter.id);loadWeaponProficiency(selectedCharacter.id)}else setWeaponProficiency({})},[selectedCharacter,loadRelations,loadWeaponProficiency]);

  const patchCharacter=async(patch:Partial<Character>)=>{if(!selectedCharacter)return;setSaving(true);const {data,error}=await supabase.from('characters').update(patch).eq('id',selectedCharacter.id).eq('player_id',player.id).select().single();if(!error&&data){const c=data as Character;setSelectedCharacter(c);setCharacters(xs=>xs.map(x=>x.id===c.id?c:x))}setSaving(false)};
  const adjustResource=async(kind:'current_hp'|'current_mp',delta:number)=>{if(!selectedCharacter||saving)return;const max=kind==='current_hp'?maxHp(selectedCharacter):maxMp(selectedCharacter);const current=kind==='current_hp'?(selectedCharacter.current_hp??max):(selectedCharacter.current_mp??max);const next=Math.max(0,Math.min(max,current+delta));if(next===current)return;await patchCharacter({[kind]:next} as Partial<Character>)};
  const cropThumbnailToThreeByFour=async(file:File)=>{const url=URL.createObjectURL(file);try{const image=await new Promise<HTMLImageElement>((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=url});const targetRatio=3/4;let sx=0,sy=0,sw=image.naturalWidth,sh=image.naturalHeight;if(sw/sh>targetRatio){sw=sh*targetRatio;sx=(image.naturalWidth-sw)/2}else{sh=sw/targetRatio;sy=(image.naturalHeight-sh)/2}const canvas=document.createElement('canvas');canvas.width=900;canvas.height=1200;const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Canvas indisponível');ctx.drawImage(image,sx,sy,sw,sh,0,0,canvas.width,canvas.height);return await new Promise<Blob>((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('Falha ao preparar miniatura')),'image/jpeg',.9))}finally{URL.revokeObjectURL(url)}};
  const uploadThumbnail=async(file?:File)=>{if(!file||!selectedCharacter)return;if(!file.type.startsWith('image/'))return;setUploading(true);try{const cropped=await cropThumbnailToThreeByFour(file);const path=`${selectedCharacter.id}/miniatura.jpg`;const {error}=await supabase.storage.from('character-thumbnails').upload(path,cropped,{upsert:true,contentType:'image/jpeg'});if(!error){const {data}=supabase.storage.from('character-thumbnails').getPublicUrl(path);await patchCharacter({thumbnail_url:`${data.publicUrl}?v=${Date.now()}`})}}finally{setUploading(false)}};

  const saveHistory=async()=>{if(!selectedCharacter)return;const keys=['nickname','gender','height','weight','appearance','distinctive_marks','origin','previous_occupation','personality','ideals','motivation','important_bond','brief_history','additional_characteristics'] as const;const patch:Record<string,string|null>={};keys.forEach(k=>patch[k]=historyDraft[k]?.trim()||null);await patchCharacter(patch as Partial<Character>);setEditingHistory(false)};
  const startHistory=()=>{if(!selectedCharacter)return;const d:Record<string,string>={};['nickname','gender','height','weight','appearance','distinctive_marks','origin','previous_occupation','personality','ideals','motivation','important_bond','brief_history','additional_characteristics'].forEach(k=>d[k]=String((selectedCharacter as unknown as Record<string,unknown>)[k]??''));setHistoryDraft(d);setEditingHistory(true)};

  const addRow=async(table:string,row:Record<string,unknown>)=>{if(!selectedCharacter)return;await supabase.from(table).insert({character_id:selectedCharacter.id,...row});await loadRelations(selectedCharacter.id)};
  const deleteRow=async(table:string,id:string)=>{if(!selectedCharacter)return;await supabase.from(table).delete().eq('id',id).eq('character_id',selectedCharacter.id);await loadRelations(selectedCharacter.id)};
  const addItem=async()=>{const name=prompt('Nome do item:');if(!name)return;const type=prompt('Tipo (comum, arma, armadura, consumível, importante):','comum')||'comum';const description=prompt('Descrição (opcional):')||null;await addRow('character_items',{name,type,quantity:1,equipped:false,description})};
  const addCatalogWeapon=async()=>{if(!selectedCharacter||!weaponChoice)return;const weapon=weaponCatalog.find(w=>w.id===weaponChoice);if(!weapon)return;await addRow('character_items',{name:weapon.name,type:'arma',quantity:1,equipped:false,description:null,weapon_id:weapon.id});setWeaponChoice('');await loadWeaponProficiency(selectedCharacter.id)};
  const editItem=async(i:Item)=>{if(!selectedCharacter)return;const name=prompt('Nome do item:',i.name);if(!name)return;const quantity=Math.max(0,Number(prompt('Quantidade:',String(i.quantity)))||0);const description=prompt('Descrição:',i.description||'');if(description===null)return;await supabase.from('character_items').update({name,quantity,description:description||null}).eq('id',i.id).eq('character_id',selectedCharacter.id);await loadRelations(selectedCharacter.id)};
  const addJourney=async(table:string)=>{const configs:Record<string,[string,string]>={character_contacts:['name','Nome do contato/aliado'],character_factions:['faction_name','Nome da facção'],character_reputations:['group_or_place','Grupo ou lugar'],character_objectives:['objective','Objetivo'],character_events:['title','Título do acontecimento']};const cfg=configs[table];const main=prompt(`${cfg[1]}:`);if(!main)return;const notes=prompt('Observações/descrição (opcional):')||null;const row:Record<string,unknown>={[cfg[0]]:main};if(table==='character_contacts'||table==='character_factions')row[table==='character_contacts'?'notes':'notes']=notes;if(table==='character_reputations')row.notes=notes;if(table==='character_objectives'){row.notes=notes;row.status='active'}if(table==='character_events')row.description=notes;await addRow(table,row)};
  const editJourney=async(table:string,id:string,currentTitle:string,currentNotes:string)=>{if(!selectedCharacter)return;const configs:Record<string,string>={character_contacts:'name',character_factions:'faction_name',character_reputations:'group_or_place',character_objectives:'objective',character_events:'title'};const title=prompt('Nome/Título:',currentTitle);if(!title)return;const notes=prompt('Observações/descrição:',currentNotes);if(notes===null)return;const patch:Record<string,unknown>={[configs[table]]:title};if(table==='character_events')patch.description=notes||null;else patch.notes=notes||null;await supabase.from(table).update(patch).eq('id',id).eq('character_id',selectedCharacter.id);await loadRelations(selectedCharacter.id)};
  const addDiary=async()=>{if(!selectedCharacter||!diaryTitle.trim()||!diaryContent.trim()||diarySaving)return;setDiarySaving(true);await addRow('character_diary',{title:diaryTitle.trim(),content:diaryContent.trim(),session_reference:diarySession.trim()||null});setDiaryTitle('');setDiaryContent('');setDiarySession('');setDiarySaving(false)};
  const editDiary=async(d:DiaryEntry)=>{if(!selectedCharacter)return;const title=prompt('Título:',d.title);if(!title)return;const content=prompt('Conteúdo:',d.content);if(content===null)return;await supabase.from('character_diary').update({title,content,updated_at:new Date().toISOString()}).eq('id',d.id);await loadRelations(selectedCharacter.id)};

  const handleSaveNotes=async()=>{if(notesSaving)return;setNotesSaving(true);setNotesSaved(false);if(notes.length){await supabase.from('personal_notes').update({content:notesContent,updated_at:new Date().toISOString()}).eq('id',notes[0].id)}else{const {data}=await supabase.from('personal_notes').insert({player_id:player.id,content:notesContent}).select().single();if(data)setNotes([data])}setNotesSaved(true);setTimeout(()=>setNotesSaved(false),2000);setNotesSaving(false)};
  const handleSendSuggestion=async()=>{if(!suggestionText.trim()||suggestionSending)return;setSuggestionSending(true);await supabase.from('suggestions').insert({player_id:player.id,content:suggestionText.trim()});setSuggestionText('');setSuggestionSent(true);setTimeout(()=>{setSuggestionSent(false);setSuggestionOpen(false)},1500);setSuggestionSending(false)};
  const authorizePlayer=async(p:Player,allowed:boolean)=>{await supabase.from('players').update({character_creation_allowed:allowed}).eq('id',p.id);await loadMasterData()};
  const changeStatus=async(c:Character,status:Character['status'])=>{await supabase.from('characters').update({status}).eq('id',c.id);await loadMasterData();if(c.player_id===player.id)await loadCharacters()};

  const canCreate=characters.length===0||Boolean(player.character_creation_allowed)||isMaster;
  const tabs:[Tab,string][]=[['ficha','Ficha'],['combate','Combate'],['inventario','Inventário'],['historia','História'],['jornada','Jornada'],['diario','Diário'],['classes','Classes'],['regras','Regras']];
  const legacyRace=selectedCharacter?ancestryRaces.find(r=>r.name===selectedCharacter.race):undefined;
  const legacyLineage=legacyRace?.lineages.find(l=>l.name===selectedCharacter?.lineage);
  const hasRacialBonus=!!selectedCharacter&&Object.keys(selectedCharacter.racial_attribute_bonus||{}).length>0;
  const hasLineageBonus=!!selectedCharacter&&Object.keys(selectedCharacter.lineage_skill_bonuses||{}).length>=2;
  const ancestryPending=!!selectedCharacter&&!!legacyRace&&!!legacyLineage&&(!hasRacialBonus||!hasLineageBonus);
  const allAttributeNames=ATTRIBUTE_GROUPS.flatMap(g=>g.attributes.map(a=>a.name));
  const skillsForGroup=(name:string)=>SKILL_GROUPS.find(g=>g.name===name)?.skills.map(x=>x.name)||[];
  const legacyFixedAttribute=legacyRace?.attribute_mode==='fixed'?legacyRace.fixed_attribute||'':'';
  const legacyAttributeValue=legacyFixedAttribute||legacyAttribute;
  const saveLegacyAncestry=async()=>{if(!selectedCharacter||!legacyRace||!legacyLineage||legacySaving)return;const attr=hasRacialBonus?selectedCharacter.racial_attribute_bonus||{}:(legacyAttributeValue?{[legacyAttributeValue]:1}:{});const skill1=hasLineageBonus?'':legacySkill1;const skill2=hasLineageBonus?'':legacySkill2;if(!hasRacialBonus&&!legacyAttributeValue)return;if(!hasLineageBonus&&(!skill1||!skill2||skill1===skill2))return;setLegacySaving(true);const skills=hasLineageBonus?selectedCharacter.lineage_skill_bonuses||{}:{[skill1]:1,[skill2]:1};const {data,error}=await supabase.from('characters').update({racial_attribute_bonus:attr,lineage_skill_bonuses:skills}).eq('id',selectedCharacter.id).eq('player_id',player.id).select().single();if(error)alert(error.message);else if(data){const c=data as Character;setSelectedCharacter(c);setCharacters(xs=>xs.map(x=>x.id===c.id?c:x));setLegacyAttribute('');setLegacySkill1('');setLegacySkill2('')}setLegacySaving(false)};

  const classUnlockCounts=useMemo(()=>Object.fromEntries(characters.map(character=>[character.id,classUnlockCount(character,classNodes)])),[characters,classNodes]);
  const selectedUnlockCount=selectedCharacter?(classUnlockCounts[selectedCharacter.id]||0):0;

  const calcCards=selectedCharacter?[
    ['PV',`${selectedCharacter.current_hp??maxHp(selectedCharacter)} / ${maxHp(selectedCharacter)}`,<>PV Máximo = 15 + (Vigor × 5) + ((Nível − 1) × 2). Seu máximo: <b>{maxHp(selectedCharacter)}</b>.</>],
    ['PM',`${selectedCharacter.current_mp??maxMp(selectedCharacter)} / ${maxMp(selectedCharacter)}`,<>5 + (Maior Mental × 2) + (Maior Mística × 2) + Nível. Sem habilidade mística, PM Máximo = 0. Seu máximo: <b>{maxMp(selectedCharacter)}</b>.</>],
    ['Evasão',String(v(selectedCharacter,'Agilidade')+s(selectedCharacter,'Defesa')),<>Agilidade + Defesa = {v(selectedCharacter,'Agilidade')} + {s(selectedCharacter,'Defesa')} = <b>{v(selectedCharacter,'Agilidade')+s(selectedCharacter,'Defesa')}</b>.</>],
    ['Bloqueio',String(v(selectedCharacter,'Força')+s(selectedCharacter,'Defesa')),<>Força + Defesa = {v(selectedCharacter,'Força')} + {s(selectedCharacter,'Defesa')} = <b>{v(selectedCharacter,'Força')+s(selectedCharacter,'Defesa')}</b>.</>],
    ['Def. Passiva',String(Math.floor(s(selectedCharacter,'Defesa')/2)),<>Defesa ÷ 2, arredondado para baixo = <b>{Math.floor(s(selectedCharacter,'Defesa')/2)}</b> sucesso(s) automático(s).</>],
    ['Iniciativa',String(v(selectedCharacter,'Percepção')+s(selectedCharacter,'Vigilância')),<>Percepção + Vigilância = <b>{v(selectedCharacter,'Percepção')+s(selectedCharacter,'Vigilância')}</b>.</>],
    ['Deslocamento',`${movement(selectedCharacter)} m`,<>6 + máx.(1, piso((Agilidade + Atletismo) ÷ 2)) = <b>{movement(selectedCharacter)} m</b>.</>],
    ['Defesas','1 reação',<>A Reação Defensiva é recuperada quando chega novamente o turno do personagem.</>]
  ]:[];

  return <div className="min-h-screen bg-gradient-fantasy animate-fade-in">
    <header className="sticky top-0 z-20 bg-shadow/80 backdrop-blur-md border-b border-gold-dim"><div className="max-w-5xl mx-auto px-4 sm:px-6 py-4 flex items-center justify-between"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-full bg-gradient-card border border-gold-dim flex items-center justify-center"><User className="w-5 h-5 text-gold"/></div><h1 className="font-display text-lg sm:text-xl text-gold-bright">Bem-vindo, {player.player_name||player.alcunha}</h1></div><button onClick={onLogout} className="flex items-center gap-2 text-parchment-dim hover:text-blood text-sm"><LogOut className="w-4 h-4"/>Sair</button></div></header>
    <main className="max-w-5xl mx-auto px-4 sm:px-6 py-8 space-y-8">
      <section className="trilha-player-characters"><div className="trilha-player-section-title"><Scroll className="w-5 h-5"/><h2 className="font-display">Meus Personagens</h2><i/></div>{charactersLoading?<div className="trilha-player-loading"><Loader2 className="w-6 h-6 animate-spin"/></div>:characters.length===0?<div className="trilha-player-empty">Você ainda não possui personagens.</div>:<div className="trilha-character-grid">{characters.map(c=><button key={c.id} onClick={()=>{setSelectedCharacter(c);setTab('ficha')}} className="trilha-character-card"><div className="trilha-character-card-portrait">{c.thumbnail_url?<img src={c.thumbnail_url} alt={`Miniatura de ${c.name}`}/>:<User className="w-10 h-10"/>}<span className="trilha-character-level">Nv. {c.level}</span></div><div className="trilha-character-card-body"><h3 className="font-display">{c.name}</h3>{c.nickname&&<p className="trilha-character-nickname">“{c.nickname}”</p>}<div className="trilha-character-card-rule"/><p className="trilha-character-lineage">{c.race} · {c.lineage}</p><p className="trilha-character-stage">{stageForLevel(c.level)} · {statusLabel(c.status)}</p>{(classUnlockCounts[c.id]||0)>0&&<div className="mt-2 flex flex-wrap items-center gap-1" title={`${classUnlockCounts[c.id]} possibilidade(s) de evolução percebida(s). As identidades continuam ocultas.`}><span className="mr-1 text-[10px] uppercase tracking-[.14em] text-gold/70">Caminhos</span>{Array.from({length:classUnlockCounts[c.id]},(_,i)=><span key={i} className="text-gold-bright text-sm" aria-hidden="true">✦</span>)}</div>}<span className="trilha-open-sheet">Abrir ficha <b>→</b></span></div></button>)}</div>}<div className="trilha-create-character">{canCreate?<button onClick={onCreateCharacter}><Plus className="w-4 h-4"/>Criar novo personagem</button>:<div><Lock className="w-4 h-4"/>Novo personagem requer autorização do Mestre.</div>}</div></section>

      {isMaster&&<><div className="divider-gold"/><section><h2 className="font-display text-xl text-gold-bright mb-4">Painel do Mestre</h2><div className="grid lg:grid-cols-2 gap-4"><div className="bg-gradient-card border border-gold-dim rounded-xl p-5"><h3 className="font-display text-gold mb-3">Autorizar novo personagem</h3><div className="space-y-2">{allPlayers.filter(p=>p.id!==player.id).map(p=><div key={p.id} className="flex items-center justify-between bg-shadow/40 rounded-lg p-3"><span className="text-sm">{p.player_name||p.alcunha}</span><button onClick={()=>authorizePlayer(p,!p.character_creation_allowed)} className="text-xs text-gold flex gap-1">{p.character_creation_allowed?<><Ban className="w-4 h-4"/>Revogar</>:<><Check className="w-4 h-4"/>Autorizar</>}</button></div>)}</div></div><div className="bg-gradient-card border border-gold-dim rounded-xl p-5"><h3 className="font-display text-gold mb-3">Status dos personagens</h3><div className="space-y-2">{allCharacters.map(c=><div key={c.id} className="flex items-center justify-between gap-3 bg-shadow/40 rounded-lg p-3"><span className="text-sm">{c.name}</span><select value={c.status||'vivo'} onChange={e=>changeStatus(c,e.target.value as Character['status'])} className="bg-shadow border border-gold-dim rounded px-2 py-1 text-xs text-parchment"><option value="vivo">Vivo</option><option value="morto">Morto</option><option value="desaparecido">Desaparecido</option></select></div>)}</div></div></div></section></>}

      <div className="divider-gold"/><section><div className="flex items-center gap-3 mb-4"><Scroll className="w-5 h-5 text-gold"/><h2 className="font-display text-xl text-gold-bright">Anotações Pessoais</h2></div><div className="trilha-player-paper border border-gold-dim rounded-xl p-4 sm:p-6 shadow-gold">{notesLoading?<Loader2 className="w-6 h-6 text-gold animate-spin mx-auto"/>:<><textarea value={notesContent} onChange={e=>setNotesContent(e.target.value)} rows={5} className={`${field} resize-y`} placeholder="Escreva seus lembretes aqui..."/><div className="flex justify-end mt-3"><button onClick={handleSaveNotes} disabled={notesSaving} className="flex gap-2 text-sm text-gold"><Save className="w-4 h-4"/>{notesSaved?'Salvo!':'Salvar'}</button></div></>}</div></section>
      <div className="divider-gold"/><section><div className="flex items-center gap-3 mb-4"><MessageSquare className="w-5 h-5 text-gold"/><h2 className="font-display text-xl text-gold-bright">Recados do Mestre</h2></div><div className="trilha-player-paper border border-gold-dim rounded-xl p-6 shadow-gold">{masterMessages.length===0?<Empty>Nenhum recado no momento.</Empty>:masterMessages.map(m=><div key={m.id} className="bg-shadow/40 border border-gold-dim rounded-lg p-4 mb-2"><p className="text-sm whitespace-pre-wrap">{m.content}</p></div>)}</div></section>
      <div className="divider-gold"/><section>{!suggestionOpen?<button onClick={()=>setSuggestionOpen(true)} className="flex gap-2 text-parchment-dim/60 hover:text-gold text-sm"><Lightbulb className="w-4 h-4"/>Enviar sugestão</button>:<div className="trilha-player-paper border border-gold-dim rounded-xl p-5"><div className="flex justify-between"><h3 className="font-display text-gold">Enviar Sugestão</h3><button onClick={()=>setSuggestionOpen(false)}><X className="w-4 h-4"/></button></div>{suggestionSent?<p className="text-gold mt-3">Sugestão enviada.</p>:<><textarea value={suggestionText} onChange={e=>setSuggestionText(e.target.value)} rows={4} className={`${field} mt-3`}/><button onClick={handleSendSuggestion} disabled={suggestionSending||!suggestionText.trim()} className="mt-3 flex gap-2 bg-gradient-gold text-stone px-4 py-2 rounded-lg"><Send className="w-4 h-4"/>Enviar</button></>}</div>}</section>
    </main>

    {ancestryPending&&selectedCharacter&&legacyRace&&legacyLineage&&<div className="fixed inset-0 z-[70] bg-black/80 flex items-center justify-center p-4"><div className="w-full max-w-2xl bg-stone border border-gold rounded-2xl p-6 shadow-2xl"><p className="text-xs uppercase tracking-[.2em] text-gold/70">Atualização do TRILHA</p><h2 className="font-display text-2xl text-gold-bright mt-1">Características raciais pendentes</h2><p className="text-sm text-parchment-dim mt-2">{selectedCharacter.name} foi criado antes das novas regras de raça e linhagem. Faça as escolhas abaixo uma única vez. Os bônus serão guardados separadamente dos pontos normais da ficha.</p><div className="mt-5 space-y-5">{!hasRacialBonus&&<div><label className="text-sm text-gold">Bônus de raça · {legacyRace.name}</label>{legacyRace.attribute_mode==='fixed'?<div className="mt-2 border border-gold-dim rounded-lg p-3">+1 {legacyFixedAttribute}</div>:<select className={`${field} mt-2`} value={legacyAttribute} onChange={e=>setLegacyAttribute(e.target.value)}><option value="">Escolha o atributo...</option>{attributeChoices(legacyRace.attribute_mode,allAttributeNames).map(a=><option key={a} value={a}>{a}</option>)}</select>}</div>}{!hasLineageBonus&&<div><label className="text-sm text-gold">Aptidões de linhagem · {legacyLineage.name}</label><p className="text-xs text-parchment-dim mt-1">Escolha +1 em uma habilidade de <b>{legacyLineage.skill_group_1}</b> e +1 em uma de <b>{legacyLineage.skill_group_2}</b>.</p><div className="grid sm:grid-cols-2 gap-3 mt-2"><select className={field} value={legacySkill1} onChange={e=>setLegacySkill1(e.target.value)}><option value="">1ª habilidade...</option>{skillsForGroup(legacyLineage.skill_group_1).map(x=><option key={x} value={x}>{x}</option>)}</select><select className={field} value={legacySkill2} onChange={e=>setLegacySkill2(e.target.value)}><option value="">2ª habilidade...</option>{skillsForGroup(legacyLineage.skill_group_2).filter(x=>x!==legacySkill1).map(x=><option key={x} value={x}>{x}</option>)}</select></div></div>}</div><div className="flex justify-end gap-3 mt-6"><button className="text-sm text-parchment-dim" onClick={()=>setSelectedCharacter(null)}>Agora não</button><button className="bg-gradient-gold text-stone font-display px-5 py-2 rounded-lg disabled:opacity-40" disabled={legacySaving||(!hasRacialBonus&&!legacyAttributeValue)||(!hasLineageBonus&&(!legacySkill1||!legacySkill2||legacySkill1===legacySkill2))} onClick={saveLegacyAncestry}>{legacySaving?'Salvando...':'Aplicar características'}</button></div></div></div>}

    {selectedCharacter&&<div className="trilha-sheet-overlay fixed inset-0 z-50 flex items-center justify-center p-2 sm:p-5"><div className="trilha-sheet w-full max-w-6xl h-[95vh] overflow-hidden flex flex-col">
      <div className="trilha-sheet-header relative flex justify-between gap-4">
        <div className="flex gap-4 sm:gap-5 items-center relative z-10">{selectedCharacter.thumbnail_url?<img src={selectedCharacter.thumbnail_url} className="trilha-portrait w-16 sm:w-20"/>:<div className="trilha-portrait w-16 h-20 sm:w-20 sm:h-24 flex items-center justify-center"><User className="text-[#d7a33d]"/></div>}<div><div className="trilha-kicker">Ficha de personagem · TRILHA</div><h2 className="trilha-character-name font-display">{selectedCharacter.name}</h2><div className="trilha-character-meta"><span>Nível {selectedCharacter.level}</span><i/> <span>{stageForLevel(selectedCharacter.level)}</span><i/> <span>{selectedCharacter.class_name||'Sem classe'}</span><i/> <span>{statusLabel(selectedCharacter.status)}</span></div><p className="trilha-character-origin">{selectedCharacter.race} · {selectedCharacter.lineage}</p>{selectedUnlockCount>0&&<div className="mt-2 inline-flex flex-wrap items-center gap-1 rounded-full border border-[#b98032]/45 bg-black/15 px-2.5 py-1" title={`${selectedUnlockCount} possibilidade(s) de evolução percebida(s). Os nomes permanecem ocultos.`}><span className="mr-1 text-[9px] uppercase tracking-[.16em] text-[#d7a33d]/80">Caminhos percebidos</span>{Array.from({length:selectedUnlockCount},(_,i)=><span key={i} className="text-[#edc96c] text-sm leading-none" aria-hidden="true">✦</span>)}</div>}<label className="trilha-thumbnail-action inline-flex items-center gap-1 mt-2 cursor-pointer"><ImagePlus className="w-3.5 h-3.5"/>{uploading?'Enviando...':'Alterar miniatura'}<input type="file" accept="image/*" className="hidden" disabled={uploading} onChange={e=>uploadThumbnail(e.target.files?.[0])}/></label></div></div><button className="trilha-sheet-close relative z-10" onClick={()=>setSelectedCharacter(null)} aria-label="Fechar ficha"><X className="w-5 h-5"/></button></div>
      <div className="trilha-tabs flex overflow-x-auto">{tabs.map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`trilha-tab whitespace-nowrap font-display ${tab===id?'is-active':''}`}>{label}</button>)}</div>
      <div className={`trilha-sheet-content overflow-y-auto flex-1 ${tab !== 'ficha' ? 'trilha-secondary-tab' : ''}`}>
        {tab==='ficha'&&<div className="trilha-ficha space-y-8">
          <section className="trilha-resource-strip">{calcCards.slice(0,2).map(([label,value,tip],index)=><div key={String(label)} className={`trilha-resource ${index===0?'is-hp':'is-mp'}`}><div className="trilha-resource-label">{label}<Tip>{tip}</Tip></div><div className="trilha-resource-value font-display">{value}</div><div className="trilha-resource-rule"/></div>)}</section>
          <section><div className="trilha-section-heading"><span>01</span><h3 className="font-display">Atributos</h3><i/></div><div className="grid md:grid-cols-3 gap-4">{ATTRIBUTE_GROUPS.map(g=><div key={g.name} className="trilha-stat-card"><h4 className="font-display">{g.name}</h4>{g.attributes.map(a=><div key={a.name} className="trilha-stat-row"><span>{a.name}<Tip><b>{a.description}</b><br/>{a.examples}</Tip></span><span className="flex items-center gap-2"><Dots base={selectedCharacter.attributes?.[a.name]??0} bonus={selectedCharacter.racial_attribute_bonus?.[a.name]??0} bonusTitle="Bônus racial"/></span></div>)}</div>)}</div></section>
          <section><div className="trilha-section-heading"><span>02</span><h3 className="font-display">Habilidades</h3><i/></div><p className="trilha-section-note">As 48 habilidades permanecem visíveis para que a evolução do personagem possa ser acompanhada desde o início.</p><div className="grid lg:grid-cols-2 gap-4">{SKILL_GROUPS.map(g=><div key={g.name} className="trilha-skill-card"><h4 className="font-display">{g.name}</h4>{g.skills.map(sk=><div key={sk.name} className="trilha-stat-row"><span>{sk.name}<Tip><b>{sk.description}</b><br/>{sk.examples}</Tip></span><span className="flex items-center gap-2"><Dots base={selectedCharacter.skills?.[sk.name]??0} bonus={selectedCharacter.lineage_skill_bonuses?.[sk.name]??0} bonusTitle="Bônus de linhagem"/></span></div>)}</div>)}</div></section>
          <div className="trilha-lock-note"><Lock className="w-4 h-4"/>Atributos, habilidades e progressão são alterados apenas pelas regras de evolução do personagem.</div>
        </div>}
        {tab==='combate'&&<div className="space-y-6"><div className="grid md:grid-cols-2 gap-4">{([['PV','current_hp',maxHp(selectedCharacter),selectedCharacter.current_hp??maxHp(selectedCharacter),calcCards[0][2]],['PM','current_mp',maxMp(selectedCharacter),selectedCharacter.current_mp??maxMp(selectedCharacter),calcCards[1][2]]] as const).map(([label,kind,max,current,tip])=><div key={label} className="bg-shadow/50 border border-gold-dim rounded-xl p-5"><div className="flex items-center justify-between mb-3"><div className="text-sm text-parchment-dim">{label}<Tip>{tip}</Tip></div><div className="font-display text-2xl text-gold-bright">{current} <span className="text-base text-parchment-dim">/ {max}</span></div></div><div className="flex items-center gap-3"><button type="button" aria-label={`Diminuir ${label}`} disabled={saving||current<=0} onClick={()=>adjustResource(kind,-1)} className="w-10 h-10 shrink-0 rounded-lg border border-gold-dim text-gold-bright text-xl disabled:opacity-30 hover:border-gold">◀</button><div className="h-3 flex-1 rounded-full bg-shadow border border-gold-dim overflow-hidden"><div className="h-full bg-gradient-gold transition-[width] duration-200" style={{width:`${max>0?(current/max)*100:0}%`}}/></div><button type="button" aria-label={`Aumentar ${label}`} disabled={saving||current>=max} onClick={()=>adjustResource(kind,1)} className="w-10 h-10 shrink-0 rounded-lg border border-gold-dim text-gold-bright text-xl disabled:opacity-30 hover:border-gold">▶</button></div></div>)}</div><div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-3">{calcCards.slice(2).map(([label,value,tip])=><div key={String(label)} className="bg-shadow/50 border border-gold-dim rounded-lg p-4"><div className="text-xs text-parchment-dim">{label}<Tip>{tip}</Tip></div><div className="font-display text-xl text-gold-bright mt-1">{value}</div></div>)}</div><p className="text-xs text-parchment-dim">Use as setas para controlar PV e PM atuais. Cada clique é salvo no personagem; os máximos continuam calculados automaticamente. {saving&&'Salvando...'}</p><section><h3 className="font-display text-gold mb-3 flex gap-2"><Shield className="w-5 h-5"/>Condições & Efeitos</h3>{conditions.length===0&&effects.length===0?<Empty/>:<div className="grid sm:grid-cols-2 gap-3">{conditions.map(c=><div key={c.id} className="bg-shadow/40 border border-gold-dim rounded-lg p-3"><b>{c.condition}</b><p className="text-xs">{renderCharacterText(c.notes, selectedCharacter)}</p></div>)}{effects.map(e=><div key={e.id} className="bg-shadow/40 border border-gold-dim rounded-lg p-3"><b>{e.name}</b><p className="text-xs">{renderCharacterText(e.description, selectedCharacter)}</p></div>)}</div>}</section></div>}
        {tab==='classes'&&<ClassDiscoveryTree character={selectedCharacter} nodes={classNodes}/>}
        {tab==='regras'&&<RulesPanel playerName={player.player_name||player.alcunha}/>}
        {tab==='inventario'&&<div><div className="flex flex-wrap justify-between items-center gap-3 mb-4"><h3 className="font-display text-lg text-gold flex gap-2"><Backpack className="w-5 h-5"/>Equipamentos & Inventário</h3><button onClick={addItem} className="text-sm text-gold flex gap-1"><Plus className="w-4 h-4"/>Adicionar item livre</button></div>{weaponCatalog.length>0&&<div className="mb-4 rounded-xl border border-gold-dim bg-shadow/40 p-3"><p className="text-xs uppercase tracking-[.14em] text-gold/70 mb-2">Adicionar arma do catálogo</p><div className="flex flex-col sm:flex-row gap-2"><select value={weaponChoice} onChange={e=>setWeaponChoice(e.target.value)} className={`${field} flex-1`}><option value="">Escolha uma arma...</option>{weaponCatalog.map(w=><option key={w.id} value={w.id}>{w.name} · {w.family}</option>)}</select><button disabled={!weaponChoice} onClick={addCatalogWeapon} className="rounded-lg border border-gold-dim px-4 py-2 text-sm text-gold disabled:opacity-40 hover:border-gold"><Plus className="w-4 h-4 inline mr-1"/>Adicionar arma</button></div><p className="text-[11px] text-parchment-dim mt-2">As especificações e requisitos da arma são mantidos pelo Mestre.</p></div>}{items.length===0?<Empty/>:<div className="grid sm:grid-cols-2 gap-3">{items.map(i=>{const proficiency=i.weapon_id?weaponProficiency[i.weapon_id]:undefined;return <div key={i.id} className="bg-shadow/40 border border-gold-dim rounded-lg p-4"><div className="flex justify-between"><b className="text-gold-bright">{i.name}</b><div className="flex gap-2"><button onClick={()=>editItem(i)}><Pencil className="w-4 h-4 text-gold"/></button><button onClick={()=>deleteRow('character_items',i.id)}><Trash2 className="w-4 h-4 text-parchment-dim"/></button></div></div><p className="text-xs text-gold">{i.type} · ×{i.quantity}{i.equipped?' · Equipado':''}</p>{i.weapon_id&&proficiency===false&&<p className="mt-2 rounded-lg border border-blood/40 bg-blood/10 px-3 py-2 text-xs text-parchment">Você ainda não é proficiente com essa arma.</p>}{i.weapon_id&&proficiency===true&&<p className="mt-2 text-xs text-gold/80">Você é proficiente com esta arma.</p>}<p className="text-sm text-parchment-dim mt-2">{i.description||'—'}</p></div>})}</div>}</div>}
        {tab==='historia'&&<div>{!editingHistory?<div className="flex justify-end mb-3"><button onClick={startHistory} className="text-sm text-gold flex gap-1"><Pencil className="w-4 h-4"/>Editar História</button></div>:<div className="flex justify-end gap-3 mb-3"><button onClick={()=>setEditingHistory(false)} className="text-sm text-parchment-dim">Cancelar</button><button onClick={saveHistory} className="text-sm text-gold flex gap-1"><Save className="w-4 h-4"/>Salvar</button></div>}<div className="grid md:grid-cols-2 gap-4">{[['Apelido','nickname'],['Gênero/Pronomes','gender'],['Altura','height'],['Peso','weight'],['Origem','origin'],['Ocupação anterior','previous_occupation'],['Aparência','appearance'],['Marcas distintivas','distinctive_marks'],['Personalidade','personality'],['Ideais / Convicções','ideals'],['Motivação','motivation'],['Vínculo importante','important_bond'],['História breve','brief_history'],['Características adicionais','additional_characteristics']].map(([label,key])=><div key={key} className="bg-shadow/40 border border-gold-dim rounded-lg p-4"><div className="text-xs text-gold mb-1">{label}</div>{editingHistory?<textarea value={historyDraft[key]||''} onChange={e=>setHistoryDraft(d=>({...d,[key]:e.target.value}))} rows={key.includes('history')||key==='appearance'?4:2} className={field}/>:<p className="text-sm text-parchment-dim whitespace-pre-wrap">{String((selectedCharacter as unknown as Record<string,unknown>)[key]||'—')}</p>}</div>)}</div></div>}
        {tab==='jornada'&&<div className="grid md:grid-cols-2 gap-4">{[
          ['character_contacts','Aliados & Contatos',contacts.map(x=>({id:x.id,t:x.name,d:[x.relationship,x.notes].filter(Boolean).join(' · ')}))],['character_factions','Facções',factions.map(x=>({id:x.id,t:x.faction_name,d:[x.relationship,x.notes].filter(Boolean).join(' · ')}))],['character_reputations','Reputações',reputations.map(x=>({id:x.id,t:x.group_or_place,d:[x.reputation,x.notes].filter(Boolean).join(' · ')}))],['character_objectives','Objetivos Atuais',objectives.map(x=>({id:x.id,t:x.objective,d:[x.status,x.notes].filter(Boolean).join(' · ')}))],['character_events','Acontecimentos Importantes',events.map(x=>({id:x.id,t:x.title,d:[x.session_reference,x.description].filter(Boolean).join(' · ')}))]
        ].map(([table,title,rows])=>{const rr=rows as {id:string;t:string;d:string}[];return <section key={String(table)} className="bg-shadow/40 border border-gold-dim rounded-lg p-4"><div className="flex justify-between"><h3 className="font-display text-gold mb-3">{String(title)}</h3><button onClick={()=>addJourney(String(table))}><Plus className="w-4 h-4 text-gold"/></button></div>{rr.length===0?<Empty/>:rr.map(x=><div key={x.id} className="mb-3 flex justify-between gap-2"><div><b className="text-sm text-gold-bright">{x.t}</b><p className="text-xs text-parchment-dim">{x.d||'—'}</p></div><div className="flex gap-2"><button onClick={()=>editJourney(String(table),x.id,x.t,x.d)}><Pencil className="w-4 h-4 text-gold"/></button><button onClick={()=>deleteRow(String(table),x.id)}><Trash2 className="w-4 h-4 text-parchment-dim"/></button></div></div>)}</section>})}</div>}
        {tab==='diario'&&<div className="grid lg:grid-cols-[1fr_1.4fr] gap-5"><section className="bg-shadow/40 border border-gold-dim rounded-lg p-4 h-fit"><h3 className="font-display text-gold mb-4">Nova entrada</h3><input value={diaryTitle} onChange={e=>setDiaryTitle(e.target.value)} placeholder="Título" className={`${field} mb-3`}/><input value={diarySession} onChange={e=>setDiarySession(e.target.value)} placeholder="Data / Sessão (opcional)" className={`${field} mb-3`}/><textarea value={diaryContent} onChange={e=>setDiaryContent(e.target.value)} rows={7} className={field}/><button onClick={addDiary} disabled={diarySaving||!diaryTitle.trim()||!diaryContent.trim()} className="mt-3 bg-gradient-gold text-stone px-4 py-2 rounded-lg">Adicionar ao diário</button></section><section><h3 className="font-display text-gold mb-4">Diário do personagem</h3>{diary.length===0?<Empty/>:<div className="space-y-3">{[...diary].reverse().map(d=><article key={d.id} className="bg-shadow/40 border border-gold-dim rounded-lg p-4"><div className="flex justify-between"><div><h4 className="font-display text-gold-bright">{d.title}</h4><p className="text-xs text-gold">{d.session_reference}</p></div><div className="flex gap-2"><button onClick={()=>editDiary(d)}><Pencil className="w-4 h-4 text-gold"/></button><button onClick={()=>deleteRow('character_diary',d.id)}><Trash2 className="w-4 h-4 text-parchment-dim"/></button></div></div><p className="text-sm text-parchment-dim whitespace-pre-wrap mt-3">{d.content}</p></article>)}</div>}</section></div>}
      </div>
    </div></div>}
  </div>;
}
